/// Represents a password group/category in the database.
///
/// Groups are used to organize password entries into categories (e.g., "Personal", "Work").
/// They support custom icons and sorting order for user organization.
class Group {
  /// Unique identifier (auto-generated by database)
  final int? id;

  /// Group name (e.g., "Personal", "Work")
  final String name;

  /// Icon identifier (optional, e.g., "home", "work")
  final String? icon;

  /// Sort order for display (default: 0)
  final int sortOrder;

  /// Timestamp when the group was created
  final DateTime createdAt;

  /// Timestamp when the group was last updated
  final DateTime updatedAt;

  /// Creates a new Group instance.
  ///
  /// [id] is optional and typically auto-generated by the database.
  /// [sortOrder] defaults to 0 if not specified.
  const Group({
    this.id,
    required this.name,
    this.icon,
    this.sortOrder = 0,
    required this.createdAt,
    required this.updatedAt,
  });

  /// Converts the Group to a Map for database storage.
  ///
  /// Uses snake_case keys to match database column names.
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'name': name,
      'icon': icon,
      'sort_order': sortOrder,
      'created_at': createdAt.millisecondsSinceEpoch,
      'updated_at': updatedAt.millisecondsSinceEpoch,
    };
  }

  /// Creates a Group from a Map (typically from database query).
  ///
  /// Expects snake_case keys matching database column names.
  factory Group.fromMap(Map<String, dynamic> map) {
    return Group(
      id: map['id'] as int?,
      name: map['name'] as String,
      icon: map['icon'] as String?,
      sortOrder: map['sort_order'] as int? ?? 0,
      createdAt: DateTime.fromMillisecondsSinceEpoch(map['created_at'] as int),
      updatedAt: DateTime.fromMillisecondsSinceEpoch(map['updated_at'] as int),
    );
  }

  /// Creates a copy of this Group with the specified fields replaced.
  ///
  /// This enables immutable updates to Group instances.
  Group copyWith({
    int? id,
    String? name,
    String? icon,
    int? sortOrder,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return Group(
      id: id ?? this.id,
      name: name ?? this.name,
      icon: icon ?? this.icon,
      sortOrder: sortOrder ?? this.sortOrder,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }

  @override
  String toString() {
    return 'Group{id: $id, name: $name, icon: $icon, sortOrder: $sortOrder}';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is Group &&
        other.id == id &&
        other.name == name &&
        other.icon == icon &&
        other.sortOrder == sortOrder &&
        other.createdAt == createdAt &&
        other.updatedAt == updatedAt;
  }

  @override
  int get hashCode {
    return Object.hash(id, name, icon, sortOrder, createdAt, updatedAt);
  }
}
