/// Represents a password entry in the database.
///
/// Each password entry belongs to a group and stores encrypted credentials
/// along with optional metadata like URLs and notes.
class PasswordEntry {
  /// Unique identifier (auto-generated by database)
  final int? id;

  /// Foreign key to the groups table
  final int groupId;

  /// Display name for the entry (e.g., "Gmail", "GitHub")
  final String title;

  /// Optional website URL
  final String? url;

  /// Optional username/email
  final String? username;

  /// Encrypted password (stored as encrypted string)
  final String password;

  /// Optional additional notes
  final String? notes;

  /// Timestamp when the entry was created
  final DateTime createdAt;

  /// Timestamp when the entry was last updated
  final DateTime updatedAt;

  /// Creates a new PasswordEntry instance.
  ///
  /// [id] is optional and typically auto-generated by the database.
  /// [url], [username], and [notes] are optional fields.
  const PasswordEntry({
    this.id,
    required this.groupId,
    required this.title,
    this.url,
    this.username,
    required this.password,
    this.notes,
    required this.createdAt,
    required this.updatedAt,
  });

  /// Converts the PasswordEntry to a Map for database storage.
  ///
  /// Uses snake_case keys to match database column names.
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'group_id': groupId,
      'title': title,
      'url': url,
      'username': username,
      'password': password,
      'notes': notes,
      'created_at': createdAt.millisecondsSinceEpoch,
      'updated_at': updatedAt.millisecondsSinceEpoch,
    };
  }

  /// Creates a PasswordEntry from a Map (typically from database query).
  ///
  /// Expects snake_case keys matching database column names.
  factory PasswordEntry.fromMap(Map<String, dynamic> map) {
    return PasswordEntry(
      id: map['id'] as int?,
      groupId: map['group_id'] as int,
      title: map['title'] as String,
      url: map['url'] as String?,
      username: map['username'] as String?,
      password: map['password'] as String,
      notes: map['notes'] as String?,
      createdAt: DateTime.fromMillisecondsSinceEpoch(map['created_at'] as int),
      updatedAt: DateTime.fromMillisecondsSinceEpoch(map['updated_at'] as int),
    );
  }

  /// Creates a copy of this PasswordEntry with the specified fields replaced.
  ///
  /// This enables immutable updates to PasswordEntry instances.
  PasswordEntry copyWith({
    int? id,
    int? groupId,
    String? title,
    String? url,
    String? username,
    String? password,
    String? notes,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return PasswordEntry(
      id: id ?? this.id,
      groupId: groupId ?? this.groupId,
      title: title ?? this.title,
      url: url ?? this.url,
      username: username ?? this.username,
      password: password ?? this.password,
      notes: notes ?? this.notes,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }

  @override
  String toString() {
    return 'PasswordEntry{id: $id, groupId: $groupId, title: $title, url: $url, username: $username}';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is PasswordEntry &&
        other.id == id &&
        other.groupId == groupId &&
        other.title == title &&
        other.url == url &&
        other.username == username &&
        other.password == password &&
        other.notes == notes &&
        other.createdAt == createdAt &&
        other.updatedAt == updatedAt;
  }

  @override
  int get hashCode {
    return Object.hash(
      id,
      groupId,
      title,
      url,
      username,
      password,
      notes,
      createdAt,
      updatedAt,
    );
  }
}
