// Mocks generated by Mockito 5.4.6 from annotations
// in apwd/test/services/webdav_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:typed_data' as _i9;

import 'package:dio/dio.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:webdav_client/src/auth.dart' as _i3;
import 'package:webdav_client/src/client.dart' as _i5;
import 'package:webdav_client/src/file.dart' as _i4;
import 'package:webdav_client/src/webdav_dio.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeWdDio_0 extends _i1.SmartFake implements _i2.WdDio {
  _FakeWdDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuth_1 extends _i1.SmartFake implements _i3.Auth {
  _FakeAuth_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFile_2 extends _i1.SmartFake implements _i4.File {
  _FakeFile_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i5.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get uri => (super.noSuchMethod(
        Invocation.getter(#uri),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#uri),
        ),
      ) as String);

  @override
  _i2.WdDio get c => (super.noSuchMethod(
        Invocation.getter(#c),
        returnValue: _FakeWdDio_0(
          this,
          Invocation.getter(#c),
        ),
      ) as _i2.WdDio);

  @override
  _i3.Auth get auth => (super.noSuchMethod(
        Invocation.getter(#auth),
        returnValue: _FakeAuth_1(
          this,
          Invocation.getter(#auth),
        ),
      ) as _i3.Auth);

  @override
  bool get debug => (super.noSuchMethod(
        Invocation.getter(#debug),
        returnValue: false,
      ) as bool);

  @override
  set c(_i2.WdDio? value) => super.noSuchMethod(
        Invocation.setter(
          #c,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set auth(_i3.Auth? value) => super.noSuchMethod(
        Invocation.setter(
          #auth,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set debug(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #debug,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setHeaders(Map<String, dynamic>? headers) => super.noSuchMethod(
        Invocation.method(
          #setHeaders,
          [headers],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setConnectTimeout(int? timeout) => super.noSuchMethod(
        Invocation.method(
          #setConnectTimeout,
          [timeout],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSendTimeout(int? timeout) => super.noSuchMethod(
        Invocation.method(
          #setSendTimeout,
          [timeout],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setReceiveTimeout(int? timeout) => super.noSuchMethod(
        Invocation.method(
          #setReceiveTimeout,
          [timeout],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> ping([_i8.CancelToken? cancelToken]) => (super.noSuchMethod(
        Invocation.method(
          #ping,
          [cancelToken],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i4.File>> readDir(
    String? path, [
    _i8.CancelToken? cancelToken,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #readDir,
          [
            path,
            cancelToken,
          ],
        ),
        returnValue: _i7.Future<List<_i4.File>>.value(<_i4.File>[]),
      ) as _i7.Future<List<_i4.File>>);

  @override
  _i7.Future<_i4.File> readProps(
    String? path, [
    _i8.CancelToken? cancelToken,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #readProps,
          [
            path,
            cancelToken,
          ],
        ),
        returnValue: _i7.Future<_i4.File>.value(_FakeFile_2(
          this,
          Invocation.method(
            #readProps,
            [
              path,
              cancelToken,
            ],
          ),
        )),
      ) as _i7.Future<_i4.File>);

  @override
  _i7.Future<void> mkdir(
    String? path, [
    _i8.CancelToken? cancelToken,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #mkdir,
          [
            path,
            cancelToken,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> mkdirAll(
    String? path, [
    _i8.CancelToken? cancelToken,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #mkdirAll,
          [
            path,
            cancelToken,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> remove(
    String? path, [
    _i8.CancelToken? cancelToken,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #remove,
          [
            path,
            cancelToken,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> removeAll(
    String? path, [
    _i8.CancelToken? cancelToken,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeAll,
          [
            path,
            cancelToken,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> rename(
    String? oldPath,
    String? newPath,
    bool? overwrite, [
    _i8.CancelToken? cancelToken,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #rename,
          [
            oldPath,
            newPath,
            overwrite,
            cancelToken,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> copy(
    String? oldPath,
    String? newPath,
    bool? overwrite, [
    _i8.CancelToken? cancelToken,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #copy,
          [
            oldPath,
            newPath,
            overwrite,
            cancelToken,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<int>> read(
    String? path, {
    void Function(
      int,
      int,
    )? onProgress,
    _i8.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [path],
          {
            #onProgress: onProgress,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i7.Future<List<int>>.value(<int>[]),
      ) as _i7.Future<List<int>>);

  @override
  _i7.Future<void> read2File(
    String? path,
    String? savePath, {
    void Function(
      int,
      int,
    )? onProgress,
    _i8.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read2File,
          [
            path,
            savePath,
          ],
          {
            #onProgress: onProgress,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> write(
    String? path,
    _i9.Uint8List? data, {
    void Function(
      int,
      int,
    )? onProgress,
    _i8.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #write,
          [
            path,
            data,
          ],
          {
            #onProgress: onProgress,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> writeFromFile(
    String? localFilePath,
    String? path, {
    void Function(
      int,
      int,
    )? onProgress,
    _i8.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #writeFromFile,
          [
            localFilePath,
            path,
          ],
          {
            #onProgress: onProgress,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}
